model:
  fea: "pha"
  norm: False
  fmamba: True
  dense_channel: 16
  edepth: 3
  mdepth: 3
  pdepth: 3
  compress_factor: 0.5
  num_tscblocks: 1
  sampling_rate: 1000
  n_fft: 512
  hop_size: 128
  win_size: 512
  beta: 1.0
  loss_fn: "time+com+con"
  mr_max_len: 9500
  mask_hp_cut_hz: 150.0
  loss_weights:
    time: 0.25
    com : 0.40
    con : 0.25
    mr  : 0.08
  use_gn: True
  gn_groups: 8
ablation:
  use_mrstft: True
  use_entropy: True
  use_phase: True

metrics:
  sampling_rate:    1000   
  n_fft:            256
  hop_size:         32
  win_size:         128
  segment_sec:      1